from typing import Dict, Union
MAX_PATH = 260

# TODO convert to enum
CENSOR_IDS: Dict[Union[str, int], Union[str, int]] = {
    "Unknown": 1, "Censored": 2, "Decensored": 3, "Uncensored": 4,
    1: "Unknown", 2: "Censored", 3: "Decensored", 4: "Uncensored"
}

STATUS_IDS: Dict[Union[str, int], Union[str, int]] = {
    "Unknown": 1, "Ongoing": 2, "Completed": 3, "Unreleased": 4, "Hiatus": 5, "Cancelled": 6,
    1: "Unknown", 2: "Ongoing", 3: "Completed", 4: "Unreleased", 5: "Hiatus", 6: "Cancelled"
}

LANG_IDS: Dict[Union[str, int], Union[str, int]] = {
     1: "Unknown",
     2: "English",
     3: "Japanese",
     4: "Chinese",
     5: "Korean",
     6: "Arabic",
     7: "Bengali",
     8: "Bulgarian",
     9: "Burmese",
    10: "Catalan",
    11: "Czech",
    12: "Danish",
    13: "Dutch",
    14: "Filipino",
    15: "Finnish",
    16: "French",
    17: "German",
    18: "Greek",
    19: "Hungarian",
    20: "Indonesian",
    21: "Italian",
    22: "Lithuanian",
    23: "Malay",
    24: "Mongolian",
    25: "Persian",
    26: "Polish",
    27: "Portuguese",
    28: "Romanian",
    29: "Russian",
    30: "Serbo-Croatian",
    31: "Spanish",
    32: "Swedish",
    33: "Thai",
    34: "Turkish",
    35: "Ukrainian",
    36: "Vietnamese",

    "Unknown": 1,
    "English": 2,
    "Japanese": 3,
    "Chinese": 4,
    "Korean": 5,
    "Arabic": 6,
    "Bengali": 7,
    "Bulgarian": 8,
    "Burmese": 9,
    "Catalan": 10,
    "Czech": 11,
    "Danish": 12,
    "Dutch": 13,
    "Filipino": 14,
    "Finnish": 15,
    "French": 16,
    "German": 17,
    "Greek": 18,
    "Hungarian": 19,
    "Indonesian": 20,
    "Italian": 21,
    "Lithuanian": 22,
    "Malay": 23,
    "Mongolian": 24,
    "Persian": 25,
    "Polish": 26,
    "Portuguese": 27,
    "Romanian": 28,
    "Russian": 29,
    "Serbo-Croatian": 30,
    "Spanish": 31,
    "Swedish": 32,
    "Thai": 33,
    "Turkish": 34,
    "Ukrainian": 35,
    "Vietnamese": 36,
}
