from typing import Dict, Union
MAX_PATH = 260

# TODO convert to enum
CENSOR_IDS: Dict[Union[str, int], Union[str, int]] = {
    "Unknown": 1, "Censored": 2, "Decensored": 3, "Uncensored": 4,
    1: "Unknown", 2: "Censored", 3: "Decensored", 4: "Uncensored"
}

STATUS_IDS: Dict[Union[str, int], Union[str, int]] = {
    "Unknown": 1, "Ongoing": 2, "Completed": 3, "Unreleased": 4, "Hiatus": 5, "Cancelled": 6,
    1: "Unknown", 2: "Ongoing", 3: "Completed", 4: "Unreleased", 5: "Hiatus", 6: "Cancelled"
}

LANG_IDS: Dict[Union[str, int], Union[str, int]] = {
     1: "English",
     2: "Japanese",
     3: "Chinese",
     4: "Korean",
     5: "Arabic",
     6: "Bengali",
     7: "Bulgarian",
     8: "Burmese",
     9: "Catalan",
    10: "Czech",
    11: "Danish",
    12: "Dutch",
    13: "Filipino",
    14: "Finnish",
    15: "French",
    16: "German",
    17: "Greek",
    18: "Hungarian",
    19: "Indonesian",
    20: "Italian",
    21: "Lithuanian",
    22: "Malay",
    23: "Mongolian",
    24: "Persian",
    25: "Polish",
    26: "Portuguese",
    27: "Romanian",
    28: "Russian",
    29: "Serbo-Croatian",
    30: "Spanish",
    31: "Swedish",
    32: "Thai",
    33: "Turkish",
    34: "Ukrainian",
    35: "Vietnamese",

    "English": 1,
    "Japanese": 2,
    "Chinese": 3,
    "Korean": 4,
    "Arabic": 5,
    "Bengali": 6,
    "Bulgarian": 7,
    "Burmese": 8,
    "Catalan": 9,
    "Czech": 10,
    "Danish": 11,
    "Dutch": 12,
    "Filipino": 13,
    "Finnish": 14,
    "French": 15,
    "German": 16,
    "Greek": 17,
    "Hungarian": 18,
    "Indonesian": 19,
    "Italian": 20,
    "Lithuanian": 21,
    "Malay": 22,
    "Mongolian": 23,
    "Persian": 24,
    "Polish": 25,
    "Portuguese": 26,
    "Romanian": 27,
    "Russian": 28,
    "Serbo-Croatian": 29,
    "Spanish": 30,
    "Swedish": 31,
    "Thai": 32,
    "Turkish": 33,
    "Ukrainian": 34,
    "Vietnamese": 35,
}
